import type { FormulaSnippetItem } from '@/react/editor/dialogs/MathDialog/FormulaSnippetButton'

export type FormulaPickerCategory = {
  id: string
  title: string
  items: FormulaSnippetItem[]
}

export const FORMULA_CATEGORIES: FormulaPickerCategory[] = [
  {
    id: 'common',
    title: 'Classical Functions',
    items: [
      { id: 'common-square', label: 'square', latex: 'x^2' },
      { id: 'common-cube', label: 'cube', latex: 'x^3' },
      { id: 'common-sqrt', label: 'square root', latex: '\\sqrt{x}' },
      { id: 'common-frac', label: 'fraction', latex: '\\frac{a}{b}' },
      { id: 'common-sin', label: 'sin', latex: '\\sin(x)' },
      { id: 'common-cos', label: 'cos', latex: '\\cos(x)' },
      { id: 'common-tan', label: 'tan', latex: '\\tan(x)' },
      { id: 'common-cot', label: 'cot', latex: '\\cot(x)' },
      { id: 'common-log', label: 'log', latex: '\\log(x)' },
      { id: 'common-ln', label: 'ln', latex: '\\ln(x)' },
      { id: 'common-lg', label: 'lg', latex: '\\lg(x)' },
      { id: 'common-exp', label: 'exponential', latex: 'e^{x}' },
      { id: 'common-abs', label: 'absolute value', latex: '|x|' },
      { id: 'common-lim', label: 'limit', latex: '\\lim_{x \\to \\infty} f(x)' },
      { id: 'common-derivative', label: 'derivative', latex: '\\frac{\\mathrm{d}y}{\\mathrm{d}x}' },
      { id: 'common-integral', label: 'indefinite integral', latex: '\\int f(x) \\,\\mathrm{d}x' },
      { id: 'common-definite', label: 'definite integral', latex: '\\int_{a}^{b} f(x) \\,\\mathrm{d}x' },
      { id: 'common-sum', label: 'summation', latex: '\\sum_{i=1}^{n} x_i' },
      { id: 'common-product', label: 'product', latex: '\\prod_{i=1}^{n} x_i' },
    ],
  },
  {
    id: 'operators',
    title: 'Operators',
    items: [
      { id: 'op-cdot', label: 'cdot', latex: '\\cdot' },
      { id: 'op-times', label: 'times', latex: '\\times' },
      { id: 'op-ast', label: 'ast', latex: '\\ast' },
      { id: 'op-div', label: 'div', latex: '\\div' },
      { id: 'op-diamond', label: 'diamond', latex: '\\diamond' },
      { id: 'op-pm', label: 'pm', latex: '\\pm' },
      { id: 'op-mp', label: 'mp', latex: '\\mp' },
      { id: 'op-oplus', label: 'oplus', latex: '\\oplus' },
      { id: 'op-ominus', label: 'ominus', latex: '\\ominus' },
      { id: 'op-otimes', label: 'otimes', latex: '\\otimes' },
      { id: 'op-emptyset', label: 'emptyset', latex: '\\emptyset' },
      { id: 'op-odot', label: 'odot', latex: '\\odot' },
      { id: 'op-circ', label: 'circ', latex: '\\circ' },
      { id: 'op-bullet', label: 'bullet', latex: '\\bullet' },
      { id: 'op-nsim', label: 'nsim', latex: '\\nsim' },
      { id: 'op-eq', label: 'equals', latex: '=' },
      { id: 'op-subset', label: 'subset', latex: '\\subset' },
      { id: 'op-supset', label: 'supset', latex: '\\supset' },
      { id: 'op-leq', label: 'leq', latex: '\\leq' },
      { id: 'op-geq', label: 'geq', latex: '\\geq' },
      { id: 'op-lneqq', label: 'lneqq', latex: '\\lneqq' },
      { id: 'op-gneqq', label: 'gneqq', latex: '\\gneqq' },
      { id: 'op-sim', label: 'sim', latex: '\\sim' },
      { id: 'op-simeq', label: 'simeq', latex: '\\simeq' },
      { id: 'op-approx', label: 'approx', latex: '\\approx' },
      { id: 'op-subseteq', label: 'subseteq', latex: '\\subseteq' },
      { id: 'op-supseteq', label: 'supseteq', latex: '\\supseteq' },
      { id: 'op-ll', label: 'll', latex: '\\ll' },
      { id: 'op-gg', label: 'gg', latex: '\\gg' },
      { id: 'op-prec', label: 'prec', latex: '\\prec' },
      { id: 'op-succ', label: 'succ', latex: '\\succ' },
      { id: 'op-infty', label: 'infty', latex: '\\infty' },
      { id: 'op-in', label: 'in', latex: '\\in' },
      { id: 'op-ni', label: 'ni', latex: '\\ni' },
      { id: 'op-forall', label: 'forall', latex: '\\forall' },
      { id: 'op-exists', label: 'exists', latex: '\\exists' },
      { id: 'op-neq', label: 'neq', latex: '\\neq' },
    ],
  },
  {
    id: 'arrows',
    title: 'Arrows',
    items: [
      { id: 'arr-left', label: 'leftarrow', latex: '\\leftarrow' },
      { id: 'arr-right', label: 'rightarrow', latex: '\\rightarrow' },
      { id: 'arr-up', label: 'uparrow', latex: '\\uparrow' },
      { id: 'arr-down', label: 'downarrow', latex: '\\downarrow' },
      { id: 'arr-lr', label: 'leftrightarrow', latex: '\\leftrightarrow' },
      { id: 'arr-ne', label: 'nearrow', latex: '\\nearrow' },
      { id: 'arr-sw', label: 'swarrow', latex: '\\swarrow' },
      { id: 'arr-nw', label: 'nwarrow', latex: '\\nwarrow' },
      { id: 'arr-se', label: 'searrow', latex: '\\searrow' },
      { id: 'arr-Left', label: 'Leftarrow', latex: '\\Leftarrow' },
      { id: 'arr-Right', label: 'Rightarrow', latex: '\\Rightarrow' },
      { id: 'arr-Up', label: 'Uparrow', latex: '\\Uparrow' },
      { id: 'arr-Down', label: 'Downarrow', latex: '\\Downarrow' },
      { id: 'arr-LR', label: 'Leftrightarrow', latex: '\\Leftrightarrow' },
    ],
  },
  {
    id: 'greek',
    title: 'Greek symbols',
    items: [
      { id: 'g-alpha', label: 'alpha', latex: '\\alpha' },
      { id: 'g-beta', label: 'beta', latex: '\\beta' },
      { id: 'g-gamma', label: 'gamma', latex: '\\gamma' },
      { id: 'g-delta', label: 'delta', latex: '\\delta' },
      { id: 'g-epsilon', label: 'epsilon', latex: '\\epsilon' },
      { id: 'g-zeta', label: 'zeta', latex: '\\zeta' },
      { id: 'g-eta', label: 'eta', latex: '\\eta' },
      { id: 'g-theta', label: 'theta', latex: '\\theta' },
      { id: 'g-iota', label: 'iota', latex: '\\iota' },
      { id: 'g-kappa', label: 'kappa', latex: '\\kappa' },
      { id: 'g-lambda', label: 'lambda', latex: '\\lambda' },
      { id: 'g-mu', label: 'mu', latex: '\\mu' },
      { id: 'g-nu', label: 'nu', latex: '\\nu' },
      { id: 'g-xi', label: 'xi', latex: '\\xi' },
      { id: 'g-pi', label: 'pi', latex: '\\pi' },
      { id: 'g-rho', label: 'rho', latex: '\\rho' },
      { id: 'g-sigma', label: 'sigma', latex: '\\sigma' },
      { id: 'g-tau', label: 'tau', latex: '\\tau' },
      { id: 'g-upsilon', label: 'upsilon', latex: '\\upsilon' },
      { id: 'g-phi', label: 'phi', latex: '\\phi' },
      { id: 'g-chi', label: 'chi', latex: '\\chi' },
      { id: 'g-psi', label: 'psi', latex: '\\psi' },
      { id: 'g-omega', label: 'omega', latex: '\\omega' },
      { id: 'g-Gamma', label: 'Gamma', latex: '\\Gamma' },
      { id: 'g-Delta', label: 'Delta', latex: '\\Delta' },
      { id: 'g-Theta', label: 'Theta', latex: '\\Theta' },
      { id: 'g-Lambda', label: 'Lambda', latex: '\\Lambda' },
      { id: 'g-Xi', label: 'Xi', latex: '\\Xi' },
      { id: 'g-Pi', label: 'Pi', latex: '\\Pi' },
      { id: 'g-Sigma', label: 'Sigma', latex: '\\Sigma' },
      { id: 'g-Upsilon', label: 'Upsilon', latex: '\\Upsilon' },
      { id: 'g-Phi', label: 'Phi', latex: '\\Phi' },
      { id: 'g-Psi', label: 'Psi', latex: '\\Psi' },
      { id: 'g-Omega', label: 'Omega', latex: '\\Omega' },
    ],
  },
  {
    id: 'advanced',
    title: 'Advanced',
    items: [
      { id: 'adv-sum', label: 'Summation', latex: '\\sum_{a}^{b} c' },
      { id: 'adv-sqrt', label: 'n-th root', latex: '\\sqrt[a]{b+c}' },
      { id: 'adv-int', label: 'Definite integral', latex: '\\int_{a}^{b} c' },
      { id: 'adv-iint', label: 'Double integral', latex: '\\iint_{a}^{b} c' },
      { id: 'adv-iiint', label: 'Triple integral', latex: '\\iiint_{a}^{b} c' },
      { id: 'adv-oint', label: 'Contour integral', latex: '\\oint_{a}' },
      { id: 'adv-paren', label: 'Parentheses', latex: '(a)' },
      { id: 'adv-brack', label: 'Square brackets', latex: '[a]' },
      { id: 'adv-brace', label: 'Curly braces', latex: '\\lbrace a \\rbrace' },
      { id: 'adv-det', label: 'Determinant', latex: '\\left|\\begin{matrix} a_1 & a_2 \\\\ a_3 & a_4 \\end{matrix} \\right|' },
      { id: 'adv-frac', label: 'Fraction', latex: '\\frac{a}{b+c}' },
      { id: 'adv-vec', label: 'Vector', latex: '\\vec{a}' },
      { id: 'adv-binom', label: 'Binomial coefficient', latex: '\\binom{a}{b}' },
      { id: 'adv-stirling1', label: 'Stirling (first kind)', latex: '\\genfrac[]{0pt}{}{a}{b}' },
      { id: 'adv-stirling2', label: 'Stirling (second kind)', latex: '\\genfrac{\\{}{\\}}{0pt}{}{a}{b}' },
    ],
  },
]
